/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiAttendanceRecordRouteImport } from './routes/api/attendance/record'
import { Route as ApiAttendanceQrRouteImport } from './routes/api/attendance/qr'
import { Route as ApiAttendanceMembersRouteImport } from './routes/api/attendance/members'
import { Route as ApiAttendanceFindMemberRouteImport } from './routes/api/attendance/find-member'
import { Route as ApiAttendanceCreateMemberRouteImport } from './routes/api/attendance/create-member'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedMeetingsNewRouteImport } from './routes/_authenticated/meetings/new'
import { Route as AuthenticatedMeetingsMeetingIdRouteImport } from './routes/_authenticated/meetings/$meetingId'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => MembersRoute,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/_authenticated/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/_authenticated/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceRecordRoute = ApiAttendanceRecordRouteImport.update({
  id: '/api/attendance/record',
  path: '/api/attendance/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceQrRoute = ApiAttendanceQrRouteImport.update({
  id: '/api/attendance/qr',
  path: '/api/attendance/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceMembersRoute = ApiAttendanceMembersRouteImport.update({
  id: '/api/attendance/members',
  path: '/api/attendance/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceFindMemberRoute = ApiAttendanceFindMemberRouteImport.update({
  id: '/api/attendance/find-member',
  path: '/api/attendance/find-member',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceCreateMemberRoute =
  ApiAttendanceCreateMemberRouteImport.update({
    id: '/api/attendance/create-member',
    path: '/api/attendance/create-member',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedMeetingsNewRoute =
  AuthenticatedMeetingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMeetingsRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdRoute =
  AuthenticatedMeetingsMeetingIdRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => AuthenticatedMeetingsRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/_authenticated/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/login': typeof LoginRoute
  '/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/members': typeof MembersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/': typeof MembersIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/api/attendance/create-member': typeof ApiAttendanceCreateMemberRoute
  '/api/attendance/find-member': typeof ApiAttendanceFindMemberRoute
  '/api/attendance/members': typeof ApiAttendanceMembersRoute
  '/api/attendance/qr': typeof ApiAttendanceQrRoute
  '/api/attendance/record': typeof ApiAttendanceRecordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/login': typeof LoginRoute
  '/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members': typeof MembersIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/api/attendance/create-member': typeof ApiAttendanceCreateMemberRoute
  '/api/attendance/find-member': typeof ApiAttendanceFindMemberRoute
  '/api/attendance/members': typeof ApiAttendanceMembersRoute
  '/api/attendance/qr': typeof ApiAttendanceQrRoute
  '/api/attendance/record': typeof ApiAttendanceRecordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/members': typeof MembersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/': typeof MembersIndexRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/_authenticated/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/api/attendance/create-member': typeof ApiAttendanceCreateMemberRoute
  '/api/attendance/find-member': typeof ApiAttendanceFindMemberRoute
  '/api/attendance/members': typeof ApiAttendanceMembersRoute
  '/api/attendance/qr': typeof ApiAttendanceQrRoute
  '/api/attendance/record': typeof ApiAttendanceRecordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/login'
    | '/meetings'
    | '/members'
    | '/settings'
    | '/dashboard'
    | '/profile'
    | '/users'
    | '/auth/signin'
    | '/demo/prisma'
    | '/members/$memberId'
    | '/members/'
    | '/admin/settings'
    | '/meetings/$meetingId'
    | '/meetings/new'
    | '/users/$userId'
    | '/api/attendance/create-member'
    | '/api/attendance/find-member'
    | '/api/attendance/members'
    | '/api/attendance/qr'
    | '/api/attendance/record'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/login'
    | '/meetings'
    | '/settings'
    | '/dashboard'
    | '/profile'
    | '/users'
    | '/auth/signin'
    | '/demo/prisma'
    | '/members/$memberId'
    | '/members'
    | '/admin/settings'
    | '/meetings/$meetingId'
    | '/meetings/new'
    | '/users/$userId'
    | '/api/attendance/create-member'
    | '/api/attendance/find-member'
    | '/api/attendance/members'
    | '/api/attendance/qr'
    | '/api/attendance/record'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/login'
    | '/meetings'
    | '/members'
    | '/settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/meetings'
    | '/_authenticated/profile'
    | '/_authenticated/users'
    | '/auth/signin'
    | '/demo/prisma'
    | '/members/$memberId'
    | '/members/'
    | '/_authenticated/admin/settings'
    | '/_authenticated/meetings/$meetingId'
    | '/_authenticated/meetings/new'
    | '/_authenticated/users/$userId'
    | '/api/attendance/create-member'
    | '/api/attendance/find-member'
    | '/api/attendance/members'
    | '/api/attendance/qr'
    | '/api/attendance/record'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  MembersRoute: typeof MembersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  ApiAttendanceCreateMemberRoute: typeof ApiAttendanceCreateMemberRoute
  ApiAttendanceFindMemberRoute: typeof ApiAttendanceFindMemberRoute
  ApiAttendanceMembersRoute: typeof ApiAttendanceMembersRoute
  ApiAttendanceQrRoute: typeof ApiAttendanceQrRoute
  ApiAttendanceRecordRoute: typeof ApiAttendanceRecordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/record': {
      id: '/api/attendance/record'
      path: '/api/attendance/record'
      fullPath: '/api/attendance/record'
      preLoaderRoute: typeof ApiAttendanceRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/qr': {
      id: '/api/attendance/qr'
      path: '/api/attendance/qr'
      fullPath: '/api/attendance/qr'
      preLoaderRoute: typeof ApiAttendanceQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/members': {
      id: '/api/attendance/members'
      path: '/api/attendance/members'
      fullPath: '/api/attendance/members'
      preLoaderRoute: typeof ApiAttendanceMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/find-member': {
      id: '/api/attendance/find-member'
      path: '/api/attendance/find-member'
      fullPath: '/api/attendance/find-member'
      preLoaderRoute: typeof ApiAttendanceFindMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/create-member': {
      id: '/api/attendance/create-member'
      path: '/api/attendance/create-member'
      fullPath: '/api/attendance/create-member'
      preLoaderRoute: typeof ApiAttendanceCreateMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/meetings/new': {
      id: '/_authenticated/meetings/new'
      path: '/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof AuthenticatedMeetingsNewRouteImport
      parentRoute: typeof AuthenticatedMeetingsRoute
    }
    '/_authenticated/meetings/$meetingId': {
      id: '/_authenticated/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdRouteImport
      parentRoute: typeof AuthenticatedMeetingsRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MembersRouteChildren {
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersMemberIdRoute: MembersMemberIdRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface AuthenticatedMeetingsRouteChildren {
  AuthenticatedMeetingsMeetingIdRoute: typeof AuthenticatedMeetingsMeetingIdRoute
  AuthenticatedMeetingsNewRoute: typeof AuthenticatedMeetingsNewRoute
}

const AuthenticatedMeetingsRouteChildren: AuthenticatedMeetingsRouteChildren = {
  AuthenticatedMeetingsMeetingIdRoute: AuthenticatedMeetingsMeetingIdRoute,
  AuthenticatedMeetingsNewRoute: AuthenticatedMeetingsNewRoute,
}

const AuthenticatedMeetingsRouteWithChildren =
  AuthenticatedMeetingsRoute._addFileChildren(
    AuthenticatedMeetingsRouteChildren,
  )

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  MembersRoute: MembersRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  ApiAttendanceCreateMemberRoute: ApiAttendanceCreateMemberRoute,
  ApiAttendanceFindMemberRoute: ApiAttendanceFindMemberRoute,
  ApiAttendanceMembersRoute: ApiAttendanceMembersRoute,
  ApiAttendanceQrRoute: ApiAttendanceQrRoute,
  ApiAttendanceRecordRoute: ApiAttendanceRecordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
