// Get Meetings
import { prisma } from '@/db';

function tryParseMeetingFromCode(code: string): { meetingId: string; date?: Date } | null {
  try {
    const raw = decodeURIComponent(code)
    const url = new URL(raw)
    const meetingId = url.searchParams.get('meeting') || url.searchParams.get('meetingId')
    const dateStr = url.searchParams.get('date')
    if (!meetingId) return null
    return { meetingId, date: dateStr ? new Date(dateStr) : undefined }
  } catch {
    return null
  }
}

export async function getMeetings() {
  return prisma.meeting.findMany()
}

// Get Meeting by ID
export async function getMeetingById(id: string) {
  return prisma.meeting.findUnique({
    where: { id },
  })
}

/**
 * Validate a QR "code" and return info about the meeting instance it represents.
 *
 * Current QR URLs generated by the app look like:
 *   /attendance?meeting=<meetingId>&date=YYYY-MM-DD
 */
export async function getMeetingDayByQrCode(code: string) {
  const parsed = tryParseMeetingFromCode(code)
  if (!parsed) return null

  const meeting = await prisma.meeting.findUnique({
    where: { id: parsed.meetingId },
    select: { id: true, exceptions: true },
  })
  if (!meeting) return null

  const date = parsed.date ?? new Date()
  const dateStr = date.toISOString().slice(0, 10)
  const isCancelled = Array.isArray(meeting.exceptions) && meeting.exceptions.includes(dateStr)

  // No explicit expiration is stored in the DB yet; treat QR codes as valid until end of that day.
  const qrCodeExpiresAt = new Date(date)
  qrCodeExpiresAt.setHours(23, 59, 59, 999)

  return {
    meetingId: meeting.id,
    date,
    isCancelled,
    qrCodeExpiresAt,
  }
}

// Create Meeting
export async function createMeeting(data: { title: string, date: Date, notes: string }) {
    return prisma.meeting.create({
        data: {
            title: data.title,
            date: data.date,
            notes: data.notes,
        },
    })
}